/* ToneLoc/Go :: THE GAME -- a complete, server-free JavaScript port of the
 * ToneLoc frontend, played as an arcade hacker game. You war-dial blocks of the
 * net looking for carriers and tones to score and clear levels, while a TRACE
 * meter climbs; honeypots spike it; hit 100% and you're BUSTED.
 *
 * The world is seeded by window.TONELOC_SEED (game/seed.js), generated by the
 * Go `toneloc-seed` tool from zmap-go's cyclic iterator -- or from a real zmap
 * scan piped through `toneloc-seed -csv`. Everything below runs in the browser
 * with no network and no backend; it renders the classic 80x25 MS-DOS screen
 * straight to a <canvas>.
 */
(function () {
  "use strict";

  // ---- DOS 16-colour VGA palette -----------------------------------------
  const PAL = [
    "#000000","#0000AA","#00AA00","#00AAAA","#AA0000","#AA00AA","#AA5500","#AAAAAA",
    "#555555","#5555FF","#55FF55","#55FFFF","#FF5555","#FF55FF","#FFFF55","#FFFFFF",
  ];
  const C = { BLACK:0,BLUE:1,GREEN:2,CYAN:3,RED:4,MAGENTA:5,BROWN:6,LGRAY:7,
    DGRAY:8,LBLUE:9,LGREEN:10,LCYAN:11,LRED:12,LMAG:13,YELLOW:14,WHITE:15 };

  const W = 80, H = 25, CW = 11, CH = 22, FS = 16;

  // ---- Cell-buffer screen -> canvas ---------------------------------------
  function Screen(canvas) {
    this.cv = canvas;
    this.cv.width = W * CW; this.cv.height = H * CH;
    this.ctx = canvas.getContext("2d");
    this.cells = new Array(W * H);
    this.clear(C.LGRAY, C.BLACK);
  }
  Screen.prototype.clear = function (fg, bg) {
    for (let i = 0; i < W * H; i++) this.cells[i] = { ch: " ", fg: fg, bg: bg };
  };
  Screen.prototype.set = function (x, y, ch, fg, bg) {
    if (x < 0 || y < 0 || x >= W || y >= H) return;
    this.cells[y * W + x] = { ch: ch || " ", fg: fg, bg: bg };
  };
  Screen.prototype.print = function (x, y, fg, bg, str) {
    str = String(str);
    for (let i = 0; i < str.length && x < W; i++, x++) this.set(x, y, str[i], fg, bg);
  };
  Screen.prototype.fill = function (x, y, w, h, ch, fg, bg) {
    for (let yy = y; yy < y + h; yy++) for (let xx = x; xx < x + w; xx++) this.set(xx, yy, ch, fg, bg);
  };
  const BOX = { d:["╔","╗","╚","╝","═","║"], s:["┌","┐","└","┘","─","│"] };
  Screen.prototype.box = function (x, y, w, h, fg, bg, dbl) {
    const b = dbl ? BOX.d : BOX.s;
    this.set(x,y,b[0],fg,bg); this.set(x+w-1,y,b[1],fg,bg);
    this.set(x,y+h-1,b[2],fg,bg); this.set(x+w-1,y+h-1,b[3],fg,bg);
    for (let i=1;i<w-1;i++){ this.set(x+i,y,b[4],fg,bg); this.set(x+i,y+h-1,b[4],fg,bg); }
    for (let i=1;i<h-1;i++){ this.set(x,y+i,b[5],fg,bg); this.set(x+w-1,y+i,b[5],fg,bg); }
  };
  Screen.prototype.title = function (x, y, w, fg, bg, t) {
    t = "► " + t + " ◄"; this.print(x + ((w - t.length) >> 1), y, fg, bg, t);
  };
  Screen.prototype.hline = function (x, y, w, fg, bg) {
    this.set(x,y,"╟",fg,bg); this.set(x+w-1,y,"╢",fg,bg);
    for (let i=1;i<w-1;i++) this.set(x+i,y,"═",fg,bg);
  };
  Screen.prototype.meter = function (x, y, w, frac, fg, track, bg) {
    frac = Math.max(0, Math.min(1, frac)); const f = (frac * w) | 0;
    for (let i=0;i<w;i++) this.set(x+i,y, i<f?"█":"▒", i<f?fg:track, bg);
  };
  Screen.prototype.render = function () {
    const ctx = this.ctx;
    ctx.textBaseline = "top";
    ctx.font = FS + 'px "DejaVu Sans Mono","Cascadia Mono","Consolas","Menlo",monospace';
    for (let y = 0; y < H; y++) {
      for (let x = 0; x < W; x++) {
        const c = this.cells[y * W + x], px = x * CW, py = y * CH;
        ctx.fillStyle = PAL[c.bg]; ctx.fillRect(px, py, CW, CH);
        if (c.ch !== " " && c.ch !== "") {
          ctx.fillStyle = PAL[c.fg];
          ctx.fillText(c.ch, px + 1, py + 3);
        }
      }
    }
  };
  const pad = (s, n) => { s = String(s); return s.length >= n ? s.slice(0, n) : s + " ".repeat(n - s.length); };
  const rpad = (s, n) => { s = String(s); return s.length >= n ? s.slice(s.length-n) : " ".repeat(n - s.length) + s; };

  // ---- seeded RNG + hashing -----------------------------------------------
  function hash32(str) { let h = 0x811c9dc5 >>> 0; for (let i=0;i<str.length;i++){ h^=str.charCodeAt(i); h=Math.imul(h,0x01000193)>>>0; } return h>>>0; }
  function mulberry32(a){ return function(){ a|=0; a=a+0x6D2B79F5|0; let t=Math.imul(a^a>>>15,1|a); t=t+Math.imul(t^t>>>7,61|t)^t; return ((t^t>>>14)>>>0)/4294967296; }; }

  // ---- the seed world ------------------------------------------------------
  const SEED = window.TONELOC_SEED || { mask:"10.0.0.0/24", ports:[23], hosts:{}, honeypots:[], meta:{} };
  const HONEY = new Set(SEED.honeypots || []);
  const PORTS = SEED.ports && SEED.ports.length ? SEED.ports : [23];

  // Build the list of /24 nets that hold enough hits to be a level.
  function buildLevels() {
    const counts = {}; // "a.b.c" -> {carriers, hits}
    for (const key in SEED.hosts) {
      const ip = key.split(":")[0]; const net = ip.split(".").slice(0,3).join(".");
      const e = counts[net] || (counts[net] = { net, hits: 0 });
      e.hits++;
    }
    const lv = Object.values(counts).filter(e => e.hits >= 4)
      .sort((a,b)=>cmpNet(a.net,b.net)).slice(0, 40);
    return lv.length ? lv : [{ net: SEED.mask.split("/")[0].split(".").slice(0,3).join("."), hits: 0 }];
  }
  function cmpNet(a,b){ const A=a.split(".").map(Number),B=b.split(".").map(Number);
    for(let i=0;i<3;i++){ if(A[i]!==B[i]) return A[i]-B[i]; } return 0; }

  // Outcomes.
  const R = { UNDIALED:0, TIMEOUT:1, BUSY:2, VOICE:3, NODT:4, RINGOUT:5, TONE:6, CARRIER:7, HONEYPOT:8 };
  const RTAG = { 1:"Timeout", 2:"Busy", 3:"Voice", 4:"No Dialtone", 5:"Ringout",
    6:"** TONE **", 7:"* CARRIER *", 8:"!! HONEYPOT !!" };
  const RPRIO = { 0:0,1:2,2:5,3:6,4:4,5:3,6:8,7:9,8:7 };

  function probe(ip, port) {
    const key = ip + ":" + port;
    if (HONEY.has(key)) return { resp: R.HONEYPOT };
    const host = SEED.hosts[key];
    if (host) return { resp: host.cls === "tone" ? R.TONE : R.CARRIER, banner: host.banner || "", svc: host.svc || "" };
    const r = mulberry32(hash32(key))();
    if (r < 0.20) return { resp: R.BUSY };
    if (r < 0.24) return { resp: R.VOICE };
    if (r < 0.28) return { resp: R.NODT };
    if (r < 0.31) return { resp: R.RINGOUT };
    return { resp: R.TIMEOUT };
  }

  function modemCode(resp, port) {
    switch (resp) {
      case R.CARRIER: return ["CONNECT 2400","CONNECT 9600","CONNECT 14400","CONNECT 33600","CONNECT 57600"][port % 5];
      case R.TONE: return "CONNECT 33600/ARQ";
      case R.HONEYPOT: return "CONNECT 31337 *TRAP*";
      case R.BUSY: return "BUSY";
      case R.NODT: return "NO DIALTONE";
      case R.VOICE: return "VOICE";
      default: return "NO CARRIER";
    }
  }

  // ---- block-letter banner font (for the splash/title) --------------------
  const FONT = {
    T:["█████","  █  ","  █  ","  █  ","  █  "], O:[" ███ ","█   █","█   █","█   █"," ███ "],
    N:["█   █","██  █","█ █ █","█  ██","█   █"], E:["█████","█    ","███  ","█    ","█████"],
    L:["█    ","█    ","█    ","█    ","█████"], C:[" ████","█    ","█    ","█    "," ████"],
    G:[" ████","█    ","█  ██","█   █"," ███ "], " ":["  ","  ","  ","  ","  "],
  };
  function banner(word){ const rows=["","","","",""]; for(const ch of word){ const g=FONT[ch]||FONT[" "];
    for(let r=0;r<5;r++) rows[r]+=g[r]+" "; } return rows; }

  // ---- game state ----------------------------------------------------------
  const MODE = { TITLE:0, PLAY:1, CLEAR:2, OVER:3 };
  const VIEW = { DIALER:0, TONEMAP:1, HOF:2 };
  const LEVELS = buildLevels();

  const G = {
    mode: MODE.TITLE, view: VIEW.DIALER,
    level: 0, score: 0, trace: 0, streak: 0, evades: 3,
    quota: 0, found: 0, dialed: 0,
    net: "", base: [0,0,0,0],
    queue: [], qi: 0,
    cur: null, dialStart: 0, dialMs: 280, meter: 0,
    waitBoost: false, paused: false,
    activity: [], modem: [], hits: [], tone: new Uint8Array(256),
    hofScroll: 0, mapCursor: 0,
    msg: "", msgUntil: 0, flash: 0,
    started: 0, lastTs: 0, frame: 0,
    sound: true,
    high: +(localStorage.getItem("toneloc_high") || 0),
  };

  function log(s){ G.activity.push(nowStr()+" "+s); if(G.activity.length>200) G.activity.shift(); }
  function modem(s){ G.modem.push(s); if(G.modem.length>40) G.modem.shift(); }
  function nowStr(){ const d=new Date(); return d.toTimeString().slice(0,8); }
  function setMsg(s, ms){ G.msg=s; G.msgUntil=performance.now()+(ms||1600); }

  function startGame(){ G.score=0; G.trace=0; G.level=0; G.evades=3; G.hits=[];
    G.mode=MODE.PLAY; startLevel(0); }

  function startLevel(n){
    const lv = LEVELS[Math.min(n, LEVELS.length-1)];
    G.level = n; G.net = lv.net; G.base = lv.net.split(".").map(Number); G.base[3]=0;
    G.quota = Math.max(3, Math.min(8, Math.round((lv.hits||6) * 0.4)));
    G.found = 0; G.dialed = 0; G.streak = 0;
    G.dialMs = Math.max(120, 300 - n*14);
    G.evades = Math.min(5, G.evades + 1);
    G.tone = new Uint8Array(256);
    G.activity = []; G.modem = [];
    // Build the shuffled (addr,port) dial queue for this /24.
    const q = [];
    for (let a=0;a<256;a++) for (const p of PORTS) q.push([a,p]);
    const rnd = mulberry32(hash32(lv.net) ^ 0x9e3779b9);
    for (let i=q.length-1;i>0;i--){ const j=(rnd()*(i+1))|0; const t=q[i];q[i]=q[j];q[j]=t; }
    G.queue = q; G.qi = 0; G.cur = null; G.meter = 0;
    G.view = VIEW.DIALER; G.mode = MODE.PLAY;
    log("ToneLoc started on "+new Date().toDateString().slice(4));
    log("Mask used:   "+G.net+".X");
    log("Ports:       "+PORTS.join(","));
    log("Quota: "+G.quota+" carriers to clear LEVEL "+(n+1));
    log("Initializing modem ... Done");
    setMsg("LEVEL "+(n+1)+" :: "+G.net+".0/24", 2200);
  }

  function ipFor(a){ return G.base[0]+"."+G.base[1]+"."+G.base[2]+"."+a; }

  function beginDial(){
    if (G.qi >= G.queue.length){ levelClear(); return; }
    const [a,p] = G.queue[G.qi++];
    G.cur = { a, p, ip: ipFor(a), port: p };
    G.dialStart = performance.now(); G.meter = 0;
    modem("ATDT "+G.cur.ip+":"+p);
  }

  function resolveDial(){
    const c = G.cur; if(!c) return;
    const res = probe(c.ip, c.port);
    G.dialed++;
    const idx = c.a;
    if (RPRIO[res.resp] >= RPRIO[G.tone[idx]]) G.tone[idx] = res.resp;
    modem(modemCode(res.resp, c.port));

    const tgt = c.ip+":"+c.port;
    switch(res.resp){
      case R.CARRIER: case R.TONE: {
        const tone = res.resp===R.TONE;
        G.streak++;
        const mult = 1 + Math.floor(G.streak/5)*0.5;
        let pts = Math.round((tone?150:100)*mult) + (res.banner?25:0);
        G.score += pts; G.found++;
        G.hits.push({ tgt, resp:res.resp, banner:res.banner, svc:res.svc });
        G.trace = Math.min(100, G.trace + 1.5); // a hit is noisy
        Sound.connect();
        log(pad(tgt,19)+" - "+RTAG[res.resp]);
        if (res.banner) modem(res.banner);
        setMsg((tone?"TONE":"CARRIER")+" +"+pts+(mult>1?"  x"+mult.toFixed(1):""), 1300);
        G.flash = 8;
        if (G.found >= G.quota) levelClear();
        break;
      }
      case R.HONEYPOT: {
        G.streak = 0; G.trace = Math.min(100, G.trace + 22); G.score = Math.max(0, G.score - 50);
        Sound.busy(); log(pad(tgt,19)+" - !! HONEYPOT - TRACE SPIKE !!");
        setMsg("*** HONEYPOT! TRACE +22 ***", 1800); G.flash = 14;
        break;
      }
      case R.BUSY: Sound.busy(); log(pad(tgt,19)+" - Busy"); break;
      case R.NODT: log(pad(tgt,19)+" - No Dialtone #1"); break;
      case R.VOICE: log(pad(tgt,19)+" - Voice"); break;
      case R.RINGOUT: log(pad(tgt,19)+" - Ringout (6)"); break;
      default: log(pad(tgt,19)+" - Timeout ("+(1+(c.a%6))+")");
    }
    G.cur = null;
  }

  function levelClear(){
    if (G.mode !== MODE.PLAY) return;
    const bonus = 500 + G.evades*100 + Math.round((100-G.trace)*5);
    G.score += bonus; G.mode = MODE.CLEAR;
    G.clearBonus = bonus; Sound.levelup();
    if (G.score > G.high){ G.high = G.score; localStorage.setItem("toneloc_high", G.high); }
  }
  function bust(){
    G.mode = MODE.OVER; Sound.gameover();
    if (G.score > G.high){ G.high = G.score; localStorage.setItem("toneloc_high", G.high); }
  }

  // ---- main loop -----------------------------------------------------------
  let scr;
  function tick(ts){
    const dt = G.lastTs ? (ts - G.lastTs)/1000 : 0; G.lastTs = ts; G.frame++;
    if (G.mode === MODE.PLAY && !G.paused){
      // Advance the dialer.
      if (!G.cur) beginDial();
      if (G.cur){
        const elapsed = ts - G.dialStart;
        const dur = G.dialMs * (G.waitBoost ? 0.4 : 1);
        G.meter = Math.min(1, elapsed / dur);
        if (elapsed >= dur) resolveDial();
      }
      // Trace climbs over time; faster on later levels and when boosting.
      const rate = (0.7 + G.level*0.2) * (G.waitBoost ? 1.7 : 1);
      G.trace = Math.min(100, G.trace + rate*dt);
      if (G.flash > 0) G.flash--;
      if (G.trace >= 100) bust();
    }
    draw();
    requestAnimationFrame(tick);
  }

  // ---- drawing -------------------------------------------------------------
  function draw(){
    const blink = ((G.frame>>4)&1)===0;
    scr.clear(C.LGRAY, C.BLACK);
    if (G.mode === MODE.TITLE) drawTitle(blink);
    else if (G.mode === MODE.OVER) drawOver(blink);
    else if (G.mode === MODE.CLEAR) drawClear(blink);
    else {
      if (G.view === VIEW.TONEMAP) drawToneMap();
      else if (G.view === VIEW.HOF) drawHOF();
      else drawDialer(blink);
    }
    scr.render();
  }

  function center(y, fg, bg, s){ scr.print((W-s.length)>>1, y, fg, bg, s); }

  function drawTitle(blink){
    for (let y=0;y<H;y++) for (let x=0;x<W;x++) scr.set(x,y, y%2?"░":" ", C.DGRAY, C.BLACK);
    const logo = banner("TONELOC"); const lx=(W-logo[0].length)>>1;
    const pal=[C.LCYAN,C.CYAN,C.LBLUE,C.LMAG,C.MAGENTA,C.YELLOW];
    for(let r=0;r<5;r++) scr.print(lx, 3+r, pal[(((G.frame/3)|0)+r)%pal.length], C.BLACK, logo[r]);
    scr.print(lx+logo[0].length-3, 8, C.LGREEN, C.BLACK, "//Go");
    center(10, C.WHITE, C.BLACK, ":: THE GAME ::  war-dial the net before the Feds trace you");
    center(12, C.LGRAY, C.BLACK, "find CARRIERS & TONES to score  ::  dodge HONEYPOTS");
    center(13, C.LGRAY, C.BLACK, "clear the quota before the TRACE meter hits 100%");
    const m = SEED.meta||{};
    center(15, C.DGRAY, C.BLACK, "world: "+(SEED.mask||"?")+"  ::  "+(m.hosts||Object.keys(SEED.hosts).length)+" services  ::  "+(HONEY.size)+" traps");
    center(16, C.DGRAY, C.BLACK, "seed: "+(m.source||"synthetic")+"  ::  "+LEVELS.length+" levels");
    if (blink) center(19, C.LGREEN, C.BLACK, "> > >   PRESS  ENTER  TO  JACK IN   < < <");
    center(21, C.YELLOW, C.BLACK, "HIGH SCORE  "+rpad(G.high,7));
    scr.print(0, 24, C.BLACK, C.LGRAY, pad(" ENTER:play   M:cycle views   C:clear-logs   B:boost   P:pause   S:sound   ESC:title", W));
  }

  function traceColor(){ return G.trace>80 ? C.LRED : G.trace>55 ? C.YELLOW : C.LGREEN; }

  function drawDialer(blink){
    // Activity Log (left).
    scr.fill(0,0,46,22," ",C.LGRAY,C.BLUE);
    scr.box(0,0,46,22,C.LCYAN,C.BLUE,true);
    scr.title(0,0,46,C.YELLOW,C.BLUE,"Activity Log");
    const lines = G.activity.slice(-20);
    for (let i=0;i<lines.length;i++){
      let fg=C.LGRAY; const ln=lines[i];
      if (ln.indexOf("CARRIER")>=0) fg=C.LGREEN; else if (ln.indexOf("TONE")>=0) fg=C.YELLOW;
      else if (ln.indexOf("HONEYPOT")>=0) fg=C.LRED; else if (ln.indexOf("Busy")>=0) fg=C.LRED;
      scr.print(2,1+i,fg,C.BLUE,pad(ln,43));
    }
    // Modem (top right).
    scr.fill(46,0,34,8," ",C.GREEN,C.BLACK); scr.box(46,0,34,8,C.LGREEN,C.BLACK,true);
    scr.title(46,0,34,C.WHITE,C.BLACK,"Modem");
    const ml = G.modem.slice(-6);
    for (let i=0;i<ml.length;i++) scr.print(48,1+i,C.LGREEN,C.BLACK,pad(ml[i],30));
    // Game panel (bottom right) -- replaces the Statistics window.
    scr.fill(46,8,34,14," ",C.LGRAY,C.BLACK); scr.box(46,8,34,14,C.LCYAN,C.BLACK,true);
    scr.title(46,8,34,C.WHITE,C.BLACK,"M I S S I O N");
    let y=10;
    const item=(label,val,vc)=>{ scr.print(48,y,C.YELLOW,C.BLACK,label); scr.print(48+label.length,y,vc||C.WHITE,C.BLACK,String(val)); y++; };
    item(" Score  : ", rpad(G.score,8), C.LGREEN);
    item(" Level  : ", (G.level+1)+" / "+LEVELS.length);
    item(" Net    : ", G.net+".X");
    item(" Found  : ", G.found+" / "+G.quota, G.found>=G.quota?C.LGREEN:C.WHITE);
    item(" Evades : ", "◄"+G.evades+"►  (C)", C.LCYAN);
    scr.hline(46,y,34,C.LCYAN,C.BLACK); scr.print(46+12,y,C.LRED,C.BLACK,"►TRACE◄"); y++;
    scr.meter(48,y,30, G.trace/100, traceColor(), C.DGRAY, C.BLACK); y++;
    scr.print(48,y,traceColor(),C.BLACK, rpad(Math.floor(G.trace)+"%",4)+(G.waitBoost?"   *BOOST*":""));
    // Dial meter + status line.
    const tgt = G.cur ? (G.cur.ip+":"+G.cur.port) : "";
    const lbl = "Dialing: "+pad(tgt,21);
    scr.print(0,22,C.WHITE,C.BLACK,lbl);
    scr.meter(0+lbl.length+1,22, W-(lbl.length+2), G.meter, C.LGREEN, C.DGRAY, C.BLACK);
    const co=[C.LCYAN,C.LMAG,C.YELLOW,C.LGREEN,C.WHITE][((G.frame/8)|0)%5];
    center(23, co, C.BLACK, "ToneLoc/Go THE GAME  ::  M:views  C:clear-logs  B:boost  P:pause  ESC:abort");
    let msg = (performance.now()<G.msgUntil)?G.msg:"";
    if (G.paused) msg="*** PAUSED -- press P ***";
    scr.print(0,24,C.BLACK,C.LGRAY,pad(" SCORE "+G.score+"   HIGH "+G.high, W));
    if (msg){ const a = G.flash>0 ? (blink?C.LRED:C.YELLOW) : C.LRED; scr.print(W-msg.length-1,24, a, C.LGRAY, msg); }
  }

  const TONE_GLYPH = {
    7:["█",C.YELLOW], 6:["█",C.LGREEN], 8:["▓",C.LRED], 2:["▓",C.LRED],
    3:["▓",C.LMAG], 4:["▒",C.LBLUE], 5:["▒",C.LCYAN], 1:["░",C.BROWN], 0:["·",C.DGRAY],
  };
  function drawToneMap(){
    scr.print(0,0,C.BLACK,C.YELLOW,pad(" ToneMap  "+G.net+".0/24   ("+G.dialed+" dialed)",W));
    const gx=2, gy=3, cols=16, rows=16;
    for(let a=0;a<256;a++){ const g=TONE_GLYPH[G.tone[a]]||TONE_GLYPH[0];
      scr.set(gx+(a%cols), gy+((a/cols)|0), g[0], g[1], C.BLACK); }
    // Legend.
    const lx=24; scr.box(lx,2,W-lx-1,12,C.LGRAY,C.BLACK,true); scr.title(lx,2,W-lx-1,C.WHITE,C.BLACK,"Key");
    const items=[[7,"Carrier"],[6,"Tone"],[2,"Busy"],[3,"Voice"],[4,"No Dialtone"],[5,"Ringout"],[1,"Timeout"],[0,"Undialed"]];
    items.forEach((it,i)=>{ const g=TONE_GLYPH[it[0]]; scr.set(lx+2,3+i,g[0],g[1],C.BLACK); scr.set(lx+3,3+i,g[0],g[1],C.BLACK);
      scr.print(lx+5,3+i,C.LGRAY,C.BLACK,it[1]); });
    scr.print(lx+2, 16, C.LCYAN, C.BLACK, "Found "+G.found+"/"+G.quota+"   Trace "+Math.floor(G.trace)+"%");
    scr.print(lx+2, 17, C.LGREEN, C.BLACK, "Score "+G.score);
    scr.print(0,24,C.BLACK,C.LGRAY,pad(" M:next view   C:clear-logs   B:boost   P:pause   ESC:abort",W));
  }

  function drawHOF(){
    scr.print(0,0,C.BLACK,C.YELLOW,pad(" Hall of Fame   "+G.hits.length+" carriers / tones bagged",W));
    const art=["  .-=====-.   ___ ___ ___ ___ ___ ___ ___ ___",
               "  \\.-----./  | _ ) __/ __/ _ \\ _ \\ __/ __|",
               "   )     (   | _ \\ _| (_| (_) |   / _|\\__ \\",
               "  /'-----'\\  |___/___\\___\\___/|_|_\\___|___/",
               "  `-=====-'"];
    art.forEach((l,i)=>scr.print(2,1+i,(i%2?C.LCYAN:C.YELLOW),C.BLACK,l));
    const top=7, h=H-1-top; scr.box(0,top-1,W,h+2,C.LGREEN,C.BLACK,true); scr.title(0,top-1,W,C.WHITE,C.BLACK,"Carriers & Tones");
    const max=Math.max(0,G.hits.length-h); if(G.hofScroll>max)G.hofScroll=max; if(G.hofScroll<0)G.hofScroll=0;
    if(!G.hits.length) scr.print(3,top+1,C.DGRAY,C.BLACK,"No carriers yet. Keep dialing.");
    for(let row=0;row<h;row++){ const i=G.hits.length-1-(row+G.hofScroll); if(i<0)break; const x=G.hits[i],y=top+row;
      scr.print(2,y,C.DGRAY,C.BLACK,rpad(G.hits.length-(row+G.hofScroll),3)+".");
      scr.print(7,y,C.WHITE,C.BLACK,pad(x.tgt,22));
      scr.print(30,y,x.resp===R.TONE?C.YELLOW:C.LGREEN,C.BLACK,pad(RTAG[x.resp],12));
      if(x.banner) scr.print(43,y,C.LCYAN,C.BLACK,pad(x.banner,W-44)); }
    scr.print(0,24,C.BLACK,C.LGRAY,pad(" M:next view   j/k or arrows:scroll   P:pause   ESC:abort",W));
  }

  function drawClear(blink){
    for(let y=0;y<H;y++)for(let x=0;x<W;x++)scr.set(x,y,y%2?"▒":" ",C.GREEN,C.BLACK);
    center(6,C.LGREEN,C.BLACK,"╔══════════════════════════════════╗");
    center(7,C.LGREEN,C.BLACK,"║        L E V E L   C L E A R       ║");
    center(8,C.LGREEN,C.BLACK,"╚══════════════════════════════════╝");
    center(11,C.WHITE,C.BLACK,"Carriers bagged: "+G.found+" / "+G.quota);
    center(12,C.YELLOW,C.BLACK,"CLEAR BONUS  +"+(G.clearBonus||0));
    center(13,C.LCYAN,C.BLACK,"Trace held at "+Math.floor(G.trace)+"%   Evades left "+G.evades);
    center(15,C.LGREEN,C.BLACK,"SCORE  "+G.score);
    if(blink) center(18,C.WHITE,C.BLACK,(G.level+1<LEVELS.length)?"PRESS ENTER FOR LEVEL "+(G.level+2):"PRESS ENTER -- FINAL SCORE");
    scr.print(0,24,C.BLACK,C.LGRAY,pad(" ENTER:continue   ESC:title",W));
  }

  function drawOver(blink){
    for(let y=0;y<H;y++)for(let x=0;x<W;x++)scr.set(x,y,y%2?"░":" ",C.RED,C.BLACK);
    center(4,C.LRED,C.BLACK,"████████████████████████████████████████");
    center(5,(blink?C.WHITE:C.LRED),C.BLACK,"   C O N N E C T I O N   T R A C E D   ");
    center(6,C.LRED,C.BLACK,"████████████████████████████████████████");
    center(8,C.YELLOW,C.BLACK,"*** BUSTED -- the trace completed ***");
    center(11,C.WHITE,C.BLACK,"Final Score   "+G.score);
    center(12,C.LGREEN,C.BLACK,"Carriers/Tones bagged: "+G.hits.length);
    center(13,C.LCYAN,C.BLACK,"Reached Level "+(G.level+1)+" of "+LEVELS.length);
    center(15,C.YELLOW,C.BLACK,(G.score>=G.high?"** NEW HIGH SCORE **  ":"HIGH SCORE  ")+G.high);
    if(blink) center(18,C.WHITE,C.BLACK,"PRESS ENTER TO TRY AGAIN");
    scr.print(0,24,C.BLACK,C.LGRAY,pad(" ENTER:retry   ESC:title",W));
  }

  // ---- input ---------------------------------------------------------------
  function clearLogs(){
    if (G.mode!==MODE.PLAY) return;
    if (G.evades<=0){ setMsg("NO EVADES LEFT!",1200); return; }
    G.evades--; G.trace=Math.max(0,G.trace-32); setMsg("LOGS CLEARED  trace -32",1400); Sound.evade();
  }

  function onKey(e){
    Sound.resume();
    const k = e.key;
    if (k==="Enter"){
      if (G.mode===MODE.TITLE) startGame();
      else if (G.mode===MODE.OVER) startGame();
      else if (G.mode===MODE.CLEAR){ if (G.level+1<LEVELS.length) startLevel(G.level+1); else { G.mode=MODE.OVER; } }
      e.preventDefault(); return;
    }
    if (k==="Escape"){ G.mode=MODE.TITLE; e.preventDefault(); return; }
    if (G.mode!==MODE.PLAY && G.mode!==MODE.CLEAR) return;
    switch(k.toLowerCase()){
      case "m": case "tab": G.view=(G.view+1)%3; e.preventDefault(); break;
      case "f": G.view=VIEW.HOF; break;
      case "c": clearLogs(); break;
      case "b": G.waitBoost=!G.waitBoost; setMsg(G.waitBoost?"BOOST ON (risky!)":"boost off",1000); break;
      case "p": G.paused=!G.paused; break;
      case "s": G.sound=!G.sound; Sound.enabled=G.sound; setMsg(G.sound?"sound on":"sound off",900); break;
      case "j": case "arrowdown": if(G.view===VIEW.HOF)G.hofScroll++; break;
      case "k": case "arrowup": if(G.view===VIEW.HOF)G.hofScroll=Math.max(0,G.hofScroll-1); break;
    }
  }

  // ---- WebAudio modem sounds ----------------------------------------------
  const Sound = (function(){
    let ctx=null,last={},hsUntil=0; const S={enabled:true};
    function ac(){ if(!S.enabled) return null; if(!ctx){ try{ctx=new (window.AudioContext||window.webkitAudioContext)();}catch(e){return null;} } if(ctx.state==="suspended")ctx.resume(); return ctx; }
    function tone(f,d,t,ty,g){ const o=ctx.createOscillator(),gn=ctx.createGain(); o.type=ty||"sine";o.frequency.value=f;o.connect(gn);gn.connect(ctx.destination);
      const a=g==null?0.13:g; gn.gain.setValueAtTime(0,t);gn.gain.linearRampToValueAtTime(a,t+0.008);gn.gain.setValueAtTime(a,t+d-0.02);gn.gain.linearRampToValueAtTime(0,t+d);o.start(t);o.stop(t+d); }
    function noise(d,t,g){ const n=Math.max(1,(ctx.sampleRate*d)|0),b=ctx.createBuffer(1,n,ctx.sampleRate),da=b.getChannelData(0);
      for(let i=0;i<n;i++)da[i]=Math.random()*2-1; const s=ctx.createBufferSource();s.buffer=b; const f=ctx.createBiquadFilter();f.type="bandpass";f.frequency.value=1900;f.Q.value=.6;
      const gn=ctx.createGain();gn.gain.value=g==null?.05:g; s.connect(f);f.connect(gn);gn.connect(ctx.destination);s.start(t);s.stop(t+d); }
    function rate(k,ms){ const n=performance.now(); if(n-(last[k]||0)<ms)return false; last[k]=n; return true; }
    return { enabled:true, resume(){ac();},
      dial(){ if(!ac()||!rate("dial",110))return; const t=ctx.currentTime; tone(941,.05,t,"sine",.06);tone(1336,.05,t,"sine",.06); },
      busy(){ if(!ac()||!rate("busy",380))return; let t=ctx.currentTime; for(let i=0;i<2;i++){tone(480,.16,t,"sine",.08);tone(620,.16,t,"sine",.08);t+=.28;} },
      evade(){ if(!ac())return; let t=ctx.currentTime; [880,660,440].forEach((f,i)=>tone(f,.08,t+i*.07,"square",.06)); },
      levelup(){ if(!ac())return; let t=ctx.currentTime; [523,659,784,1047].forEach((f,i)=>tone(f,.12,t+i*.1,"square",.07)); },
      gameover(){ if(!ac())return; let t=ctx.currentTime; [392,330,262,196].forEach((f,i)=>tone(f,.25,t+i*.22,"sawtooth",.08)); noise(1.0,t+0.9,.04); },
      connect(){ if(!ac())return; const now=performance.now(); if(now<hsUntil){tone(1100,.18,ctx.currentTime,"sine",.08);return;} hsUntil=now+2200; let t=ctx.currentTime;
        tone(350,.3,t,"sine",.05);tone(440,.3,t,"sine",.05);t+=.34;
        [[697,1209],[770,1336],[852,1477],[941,1336]].forEach(p=>{tone(p[0],.07,t,"sine",.07);tone(p[1],.07,t,"sine",.07);t+=.1;});
        t+=.1; tone(2100,.5,t,"sine",.1); t+=.5;
        for(let i=0;i<7;i++){tone(1100+(i%2?740:-260),.1,t,"square",.04);noise(.1,t,.045);t+=.1;} noise(.4,t,.03);
      },
    };
  })();

  // ---- boot ----------------------------------------------------------------
  window.addEventListener("DOMContentLoaded", function(){
    scr = new Screen(document.getElementById("cv"));
    document.addEventListener("keydown", onKey);
    document.getElementById("cv").addEventListener("click", ()=>Sound.resume());
    document.body.addEventListener("click", ()=>Sound.resume(), { once:true });
    G.started = performance.now();
    requestAnimationFrame(tick);
  });
})();
