// Command toneloc-seed produces the dataset that seeds the standalone
// JavaScript game (game/seed.js). It has two modes:
//
//   - Real data:  pipe a zmap scan in and it is converted verbatim:
//     zmap -p 22,23,80,443 -O csv -f saddr,sport,classification,success \
//     198.51.100.0/24 | toneloc-seed -csv -mask 198.51.100.0/24 > game/seed.js
//
//   - Synthetic:  with no stdin it walks the mask with zmap-go's cyclic
//     iterator (the same permutation the real scanner uses) and lights up a
//     realistic, reproducible scatter of open services and honeypots.
//
// Either way the output is a small JS file assigning window.TONELOC_SEED, so
// the game loads it with a plain <script> tag and runs from file:// with no
// server and no network.
package main

import (
	"bufio"
	"encoding/json"
	"flag"
	"fmt"
	"hash/fnv"
	"os"
	"strconv"
	"strings"

	"github.com/hdm/toneloc/internal/engine"
)

type host struct {
	Class  string `json:"cls"` // "carrier" | "tone"
	Banner string `json:"banner,omitempty"`
	Svc    string `json:"svc,omitempty"`
}

type seed struct {
	Meta      map[string]any  `json:"meta"`
	Mask      string          `json:"mask"`
	Ports     []uint16        `json:"ports"`
	Hosts     map[string]host `json:"hosts"`
	Honeypots []string        `json:"honeypots"`
}

func main() {
	maskStr := flag.String("mask", "10.37.0.0/16", "address space to seed")
	portsStr := flag.String("ports", "21,22,23,80,110,443,992,8080", "ports to seed")
	seedNum := flag.Uint64("seed", 0x744f4e45, "RNG seed for synthetic generation")
	openRate := flag.Float64("open", 0.018, "fraction of (addr,port) that answer (synthetic)")
	trapRate := flag.Float64("traps", 0.003, "fraction that are honeypots (synthetic)")
	csv := flag.Bool("csv", false, "read a zmap CSV scan from stdin instead of synthesizing")
	flag.Parse()

	mask, err := engine.ParseMask(*maskStr)
	if err != nil {
		fail(err)
	}
	ports, err := engine.ParsePorts(*portsStr)
	if err != nil {
		fail(err)
	}

	s := seed{
		Mask:      mask.CIDR().String(),
		Ports:     ports,
		Hosts:     map[string]host{},
		Honeypots: []string{},
		Meta:      map[string]any{},
	}

	if *csv {
		s.Meta["source"] = "zmap csv (real scan)"
		readCSV(&s)
	} else {
		s.Meta["source"] = "synthetic (zmap-go cyclic iterator)"
		synthesize(&s, mask, ports, *seedNum, *openRate, *trapRate)
	}
	s.Meta["generator"] = "toneloc-seed"
	s.Meta["hosts"] = len(s.Hosts)
	s.Meta["honeypots"] = len(s.Honeypots)

	blob, err := json.Marshal(s)
	if err != nil {
		fail(err)
	}
	out := bufio.NewWriter(os.Stdout)
	defer out.Flush()
	fmt.Fprintln(out, "// Generated by toneloc-seed. Seeds the standalone ToneLoc/Go JS game.")
	fmt.Fprintln(out, "// Source:", s.Meta["source"], "  hosts:", len(s.Hosts), "  honeypots:", len(s.Honeypots))
	fmt.Fprint(out, "window.TONELOC_SEED = ")
	out.Write(blob)
	fmt.Fprintln(out, ";")
}

// synthesize walks mask x ports with zmap-go's iterator and assigns outcomes
// from a stable per-target hash, so the same seed always yields the same world.
func synthesize(s *seed, mask *engine.Mask, ports []uint16, seedNum uint64, openRate, trapRate float64) {
	dialer, err := engine.NewDialer(mask, ports, nil, seedNum)
	if err != nil {
		fail(err)
	}
	for {
		addr, port, ok := dialer.Next()
		if !ok {
			break
		}
		key := addr.String() + ":" + strconv.Itoa(int(port))
		r := hashUnit(key, seedNum)
		switch {
		case r < trapRate:
			s.Honeypots = append(s.Honeypots, key)
		case r < trapRate+openRate:
			svc, banner := service(port, key, seedNum)
			cls := "carrier"
			if hashUnit(key+"#t", seedNum) < 0.45 {
				cls = "tone"
			}
			s.Hosts[key] = host{Class: cls, Banner: banner, Svc: svc}
		}
	}
}

func readCSV(s *seed) {
	sc := bufio.NewScanner(os.Stdin)
	sc.Buffer(make([]byte, 0, 1<<16), 1<<20)
	first := true
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" {
			continue
		}
		if first {
			first = false
			if strings.HasPrefix(line, "saddr") {
				continue // header
			}
		}
		f := strings.Split(line, ",")
		if len(f) < 3 {
			continue
		}
		ip, port, class := strings.TrimSpace(f[0]), strings.TrimSpace(f[1]), strings.TrimSpace(f[2])
		if class != "synack" {
			continue // only open ports become carriers/tones
		}
		key := ip + ":" + port
		var banner string
		if len(f) > 4 {
			banner = strings.TrimSpace(f[4])
		}
		p, _ := strconv.Atoi(port)
		svc, def := service(uint16(p), key, 1)
		if banner == "" {
			banner = def
		}
		cls := "carrier"
		if banner != "" {
			cls = "tone"
		}
		s.Hosts[key] = host{Class: cls, Banner: banner, Svc: svc}
	}
}

// service maps a port to a plausible service name and login banner.
func service(port uint16, key string, seedNum uint64) (string, string) {
	pool := map[uint16][]string{
		21:   {"220 ProFTPD 1.3.5 Server ready", "220 vsFTPd 3.0.3", "220 Serv-U FTP Server"},
		22:   {"SSH-2.0-OpenSSH_9.6", "SSH-2.0-OpenSSH_7.4", "SSH-1.99-Cisco-1.25"},
		23:   {"login:", "Username:", "@ Annex Command Line Interpreter", "Welcome to VMS", "Password:"},
		79:   {"Login       Name", "finger: no such user"},
		80:   {"HTTP/1.0 200 OK", "HTTP/1.1 401 Unauthorized", "<title>Index of /</title>"},
		110:  {"+OK POP3 ready", "+OK Dovecot ready"},
		443:  {"HTTP/1.1 200 OK", "TLS handshake", "<title>VPN Portal</title>"},
		992:  {"Telnet over TLS", "login:"},
		8080: {"HTTP/1.0 200 OK", "Jetty(9.4.z)", "Welcome to the admin console"},
	}
	names := map[uint16]string{21: "ftp", 22: "ssh", 23: "telnet", 79: "finger",
		80: "http", 110: "pop3", 443: "https", 992: "telnets", 8080: "http-alt"}
	svc := names[port]
	if svc == "" {
		svc = "tcp/" + strconv.Itoa(int(port))
	}
	bs := pool[port]
	if len(bs) == 0 {
		return svc, ""
	}
	idx := int(hashUnit(key+"#b", seedNum) * float64(len(bs)))
	if idx >= len(bs) {
		idx = len(bs) - 1
	}
	return svc, bs[idx]
}

// hashUnit returns a stable float in [0,1) for key+seed.
func hashUnit(key string, seedNum uint64) float64 {
	h := fnv.New64a()
	var b [8]byte
	for i := 0; i < 8; i++ {
		b[i] = byte(seedNum >> (8 * i))
	}
	h.Write(b[:])
	h.Write([]byte(key))
	return float64(h.Sum64()%1_000_000) / 1_000_000.0
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "toneloc-seed:", err)
	os.Exit(1)
}
